---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# BIONESS_rescue

This is a project which was undertaken to rescue some historical stratified net
data, primarily BIONESS data from 2009-2016. This project includes documentation
and scripts which were used to consolidate and format the data as well as extract
and supplement metadata. There is also a report (BioNess Archival Report.Rmd), 
which summarizes the workplan and the results achieved. 

## Files included

- BioNess Archival Report.Rmd - This is the report which summarizes the workplan and the results achieved.

- bioness_biochem_Summary.r - This summarizes the BIONESS data loaded to BioChem

- event_number_verify.R - This was used to check BioChem for the BIONESS event numbers

- volume_extraction.R - This was the workflow to extract volume data from
    electronic BIONESS files


### Data

- BIONESS_loaded.csv - This is the data which was loaded to BioChem prior to this 
  rescue project
  
- Data formatted and archived under this project can be found in individual 
  mission folders in SRC, in the BIONESS subfolder

